### ISSUE TITLE
unresolved name `rand::thread_rng`

### ISSUE THREAD

**Issue by andschwa** [flycheck/flycheck-rust#11]
Hello,

I have the following code which compiles fine via `cargo run`:

## `src/main.rs`
```rust
extern crate rand;

use rand::distributions::{IndependentSample, Range};

fn main() {
    let mut rng = rand::thread_rng(); // Flycheck error is here
    let range = Range::new(-512.03, 511.97);
    println!("A random number is {}", range.ind_sample(&mut rng));
}
```
## `Cargo.toml`
``` toml
[package]
name = "rando"
version = "0.1.0"
authors = ["Andrew Schwartzmeyer <andrew@schwartzmeyer.com>"]

[dependencies]
rand = "0.3"
```

However, Flycheck with `flycheck-rust` gives the warning "unresolved name `rand::thread_rng`" on line 6. It does not appear to be recognize that the function was imported from a crate.

The Flycheck project may be a better place to post this issue, but I was hoping you could help me out!

```
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
cargo 0.2.0-nightly (efb482d 2015-04-30) (built 2015-04-29)
OS X 10.10.3
GNU Emacs 24.5.50.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-04-13
Flycheck version: 0.24snapshot (package: 20150514.528)
flycheck-rust package 20150417.1048
```
I am using the [rand crate](http://doc.rust-lang.org/rand/rand/index.html).
